version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=peopledb
      - MYSQL_ROOT_PASSWORD=mypass
    networks:
      - app-network

  node-app:
    build:
      context: ./app
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build:
        context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db
      - node-app

networks:
    app-network:
      driver: bridge